/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.8
 * Generated at: 2023-05-16 00:50:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class AdminLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>LoginForm</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"bootstrap.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"margin-top: 50px;margin-left: 50px;\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <table style=\"width: 90%;\">\r\n");
      out.write("            \r\n");
      out.write("            <tr style=\"border: 2px;\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <section class=\"min-vh-50\">\r\n");
      out.write("                        <div class=\"container-fluid\">\r\n");
      out.write("                          <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-sm-6 text-black\">\r\n");
      out.write("                      \r\n");
      out.write("                              <div class=\"px-5 ms-xl-4\">\r\n");
      out.write("                                <i class=\"fas fa-crow fa-2x me-3 pt-5 mt-xl-4\" style=\"color: #709085;\"></i>\r\n");
      out.write("                                <h3 class=\"h1 fw-bold mb-0\">My NetBanking Application</h3>\r\n");
      out.write("                                <hr>\r\n");
      out.write("                                \r\n");
      out.write("                                <h3>Welcome to Admin Portal</h3>\r\n");
      out.write("                              </div>\r\n");
      out.write("                      \r\n");
      out.write("                              <div class=\"d-flex align-items-center h-custom-2 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5\">\r\n");
      out.write("                      \r\n");
      out.write("                                <form method=\"post\" action=\"AdminCheck\" style=\"width: 15rem;\">\r\n");
      out.write("                      \r\n");
      out.write("                                  <h3 class=\"fw-normal mb-3 pb-3\" style=\"letter-spacing: 1px;\">Log in here</h3>\r\n");
      out.write("                      \r\n");
      out.write("                                  <div class=\"form-outline mb-2\">\r\n");
      out.write("                                    <input type=\"text\" name=\"uid\" class=\"form-control form-control-lg\" />\r\n");
      out.write("                                    <label class=\"form-label\" for=\"form2Example18\">UserID</label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                      \r\n");
      out.write("                                  <div class=\"form-outline mb-2\">\r\n");
      out.write("                                    <input type=\"password\" name=\"psw\" class=\"form-control form-control-lg\" />\r\n");
      out.write("                                    <label class=\"form-label\" for=\"form2Example28\">Password</label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                      \r\n");
      out.write("                                  <div class=\"pt-1 mb-2\">\r\n");
      out.write("                                    <button class=\"btn btn-info btn-block\" type=\"submit\" value=\"Submit\">Login</button>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                      \r\n");
      out.write("                                  <h4 class=\"small mb-4 pb-lg-2\"><a class=\"text-muted\" href=\"#!\">Forgot password?</a></h4>\r\n");
      out.write("                                  \r\n");
      out.write("                                </form>\r\n");
      out.write("                      \r\n");
      out.write("                              </div>\r\n");
      out.write("                      \r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </section>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <h6 class=\"display-9\">&emsp;Developed by kk\r\n");
      out.write("        <br>&emsp;kapilkadu&copy;2023</h6>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
